export enum DashboardPageType {
  SEASONAL_EMP = 'seasonal_emp',
  NOMINATION = 'nomination',
  SEASONAL_DEPT = 'seasonal_dept',
  USER_PROFILE = 'user_profile',
  CENTER_CLASSIFICATION = 'center_classification',
  // ACS
  CONTRACT_TYPE = 'contract_type',
  CONTRACTOR_COMPANY = 'contractor_company',
  CONTRACTOR_TYPE = 'contractor_type',
  PROJECT = 'project',
  PROJECT_CONTRACT = 'project_contract',
  COMPANY_CONTRACTOR_REQ = 'company_contractor_req',
  // CUR
  CURRICULUM = 'curriculum',
  MILESTONE = 'milestone',
  CUR_PATH = 'cur_path',
  STAGE = 'stage',
  TASK = 'task',
  // EME
  AREA = 'area',
  CHECKLIST_ELEMENT = 'checklist_element',
  FORM_GROUP_ELEMENT = 'form_group_element',
  FORM_TYPE = 'form_type',
  JOB_TITLE = 'job_title',
  SERVICE_TYPE = 'service_type',
  TEAM = 'team',
  TEAM_JOB_ORDER = 'team_job_order',
  TEAM_TYPES = 'team_types',
  VISIT_REASON_TYPE = 'visit_reason_type',
  VISIT_TYPE = 'visit_type',
  // NTF
  MAIL_TEMPLATE = 'mail_template',
  SMS_TEMPLATE = 'sms_template',
  // SHR
  SHARE_TYPE = 'share_type',
  SHAREHOLDER_BATCH = 'shareholder_batch',
  SHAREHOLDER_DEATH = 'shareholder_death',
  SHAREHOLDER_PROFILE = 'shareholder_profile',
  SHAREHOLDER_RELATION = 'shareholder_relation',
  SHR_BATCH = 'shr_batch',
  SHR_DELEGATION_TYPE = 'shr_delegation_type',
  SHR_INHERIT_LEGACY = 'shr_inherit_legacy',
  SHR_INHERIT_ORDER = 'shr_inherit_order',
  SHR_RELATIVE = 'shr_relative',
  SHR_STATUS = 'shr_status',
  SIGN_INC_CONTRACT = 'sign_inc_contract',
  // HAJ
  AVIATION_MEMBERSHIP = 'aviation_membership',
  BUSS_INFO = 'buss_info',
  DRIVER_INFO = 'driver_info',
  EST = 'est',
  EST_BRANCH = 'est_branch',
  FOOD_COMPANY = 'food_company',
  FOOD_CONTRACT = 'food_contract',
  HAJ_COMPANY = 'haj_company',
  HOUSE = 'house',
  HOUSE_CONTRACT = 'house_contract',
  LIFTING_COMPANY = 'lifting_company',
  LIFTING_CONTRACT = 'lifting_contract',
  MISSIONS = 'missions',
  // SES
  ALLOWANCE_TYPE = 'allowance_type',
  APPROVED_JOB_CENTER = 'approved_job_center',
  CONTRACT_CONDITION = 'contract_condition',
  JOB_CATEGORY = 'job_category',
  JOB_CLASSIFICATION_TYPE = 'job_classification_type',
  JOB_LEVEL = 'job_level',
  SEASONAL_JOB_APP_SETTING = 'seasonal_job_app_setting',
  TIME_PERIOD = 'time_period',
  // DEF (Common)
  COUNTRY = 'country',
  CITY = 'city',
  NATIONALITY = 'nationality',
  BANK = 'bank',
  JOB = 'job',
  LANGUAGE = 'language',
  PORT = 'port',
  SEASON = 'season',
  TERMINAL = 'terminal',
  BUS_TYPE = 'bus_type',
  CAR_TYPE = 'car_type',
  LOCATION = 'location',
  DEPARTMENT = 'department',
  ATTACHMENT_CATEGORY = 'attachment_category',
  REPRESENTATIVE = 'representative',
  ROUTE = 'route',
  SERVER = 'server',
  DEF_PATH = 'def_path',
  PAYMENT_METHOD = 'payment_method',
  EMPLOYMENT_STATUS = 'employment_status',
  AGE_STAGE = 'age_stage',
  DEPARTMENT_TYPE = 'department_type',
  HAJ_COMPANY_TYPE = 'haj_company_type',
  HAJ_TYPE = 'haj_type',
  HOUSE_AGENT_TYPE = 'house_agent_type',
  HOUSE_BENEFIT_TYPE = 'house_benefit_type',
  HOUSE_INVESTOR_TYPE = 'house_investor_type',
  HOUSE_OWNER_TYPE = 'house_owner_type',
  HOUSE_TYPE = 'house_type',
  LAND_TRAN_COMPANY = 'land_tran_company'
}

export const DASHBOARD_PAGE_ROUTES: Record<string, string> = {
  [DashboardPageType.SEASONAL_EMP]: '/apps/ses/nafath/seasonal-job-request/user/details?mode=add',
  [DashboardPageType.NOMINATION]: '/apps/ses/nomination/hr/details?mode=add',
  [DashboardPageType.SEASONAL_DEPT]: '/apps/def/seasonal-department/details?mode=add',
  [DashboardPageType.USER_PROFILE]: '/apps/def/user-profile/details?mode=add',
  [DashboardPageType.CENTER_CLASSIFICATION]: '/apps/ses/center-classification/details?mode=add',
  // ACS
  [DashboardPageType.CONTRACT_TYPE]: '/apps/acs/contract-type/details?mode=add',
  [DashboardPageType.CONTRACTOR_COMPANY]: '/apps/acs/contractor-company/details?mode=add',
  [DashboardPageType.CONTRACTOR_TYPE]: '/apps/acs/contractor-type/details?mode=add',
  [DashboardPageType.PROJECT]: '/apps/acs/project/details?mode=add',
  [DashboardPageType.PROJECT_CONTRACT]: '/apps/acs/project-contract/details?mode=add',
  [DashboardPageType.COMPANY_CONTRACTOR_REQ]: '/apps/acs/company-contractor-request/details?mode=add',
  // CUR
  [DashboardPageType.CURRICULUM]: '/apps/cur/curriculum/details?mode=add',
  [DashboardPageType.MILESTONE]: '/apps/cur/milestone/details?mode=add',
  [DashboardPageType.CUR_PATH]: '/apps/cur/path/details?mode=add',
  [DashboardPageType.STAGE]: '/apps/cur/stage/details?mode=add',
  [DashboardPageType.TASK]: '/apps/cur/task/details?mode=add',
  // EME
  [DashboardPageType.AREA]: '/apps/eme/area/details?mode=add',
  [DashboardPageType.CHECKLIST_ELEMENT]: '/apps/eme/checklist-element/details?mode=add',
  [DashboardPageType.FORM_GROUP_ELEMENT]: '/apps/eme/form-group-element/details?mode=add',
  [DashboardPageType.FORM_TYPE]: '/apps/eme/form-type/details?mode=add',
  [DashboardPageType.JOB_TITLE]: '/apps/eme/job-title/details?mode=add',
  [DashboardPageType.SERVICE_TYPE]: '/apps/eme/service-type/details?mode=add',
  [DashboardPageType.TEAM]: '/apps/eme/team/details?mode=add',
  [DashboardPageType.TEAM_JOB_ORDER]: '/apps/eme/team-job-order/details?mode=add',
  [DashboardPageType.TEAM_TYPES]: '/apps/eme/team-types/details?mode=add',
  [DashboardPageType.VISIT_REASON_TYPE]: '/apps/eme/visit-reason-type/details?mode=add',
  [DashboardPageType.VISIT_TYPE]: '/apps/eme/visit-type/details?mode=add',
  // NTF
  [DashboardPageType.MAIL_TEMPLATE]: '/apps/ntf/mail-template/details?mode=add',
  [DashboardPageType.SMS_TEMPLATE]: '/apps/ntf/sms-template/details?mode=add',
  // SHR
  [DashboardPageType.SHARE_TYPE]: '/apps/shr/share-type/details?mode=add',
  [DashboardPageType.SHAREHOLDER_BATCH]: '/apps/shr/shareholder-batch/details?mode=add',
  [DashboardPageType.SHAREHOLDER_DEATH]: '/apps/shr/shareholder-death/details?mode=add',
  [DashboardPageType.SHAREHOLDER_PROFILE]: '/apps/shr/shareholder-profile/details?mode=add',
  [DashboardPageType.SHAREHOLDER_RELATION]: '/apps/shr/shareholder-relation/details?mode=add',
  [DashboardPageType.SHR_BATCH]: '/apps/shr/shr-batch/details?mode=add',
  [DashboardPageType.SHR_DELEGATION_TYPE]: '/apps/shr/shr-delegation-type/details?mode=add',
  [DashboardPageType.SHR_INHERIT_LEGACY]: '/apps/shr/shr-inherit-legacy/details?mode=add',
  [DashboardPageType.SHR_INHERIT_ORDER]: '/apps/shr/shr-inherit-order/details?mode=add',
  [DashboardPageType.SHR_RELATIVE]: '/apps/shr/shr-relative/details?mode=add',
  [DashboardPageType.SHR_STATUS]: '/apps/shr/shr-status/details?mode=add',
  [DashboardPageType.SIGN_INC_CONTRACT]: '/apps/shr/sign-incorporation-contract/details?mode=add',
  // HAJ
  [DashboardPageType.AVIATION_MEMBERSHIP]: '/apps/haj/aviation-membership/details?mode=add',
  [DashboardPageType.BUSS_INFO]: '/apps/haj/buss-info/details?mode=add',
  [DashboardPageType.DRIVER_INFO]: '/apps/haj/driver-info/details?mode=add',
  [DashboardPageType.EST]: '/apps/haj/est/details?mode=add',
  [DashboardPageType.EST_BRANCH]: '/apps/haj/est-branch/details?mode=add',
  [DashboardPageType.FOOD_COMPANY]: '/apps/haj/food-company/details?mode=add',
  [DashboardPageType.FOOD_CONTRACT]: '/apps/haj/food-contract/details?mode=add',
  [DashboardPageType.HAJ_COMPANY]: '/apps/haj/haj-company/details?mode=add',
  [DashboardPageType.HOUSE]: '/apps/haj/house/details?mode=add',
  [DashboardPageType.HOUSE_CONTRACT]: '/apps/haj/house-contract/details?mode=add',
  [DashboardPageType.LIFTING_COMPANY]: '/apps/haj/lifting-company/details?mode=add',
  [DashboardPageType.LIFTING_CONTRACT]: '/apps/haj/lifting-contract/details?mode=add',
  [DashboardPageType.MISSIONS]: '/apps/haj/missions/details?mode=add',
  // SES
  [DashboardPageType.ALLOWANCE_TYPE]: '/apps/ses/allowance-type/details?mode=add',
  [DashboardPageType.APPROVED_JOB_CENTER]: '/apps/ses/approved-job-center/details?mode=add',
  [DashboardPageType.CONTRACT_CONDITION]: '/apps/ses/contract-condition/details?mode=add',
  [DashboardPageType.JOB_CATEGORY]: '/apps/ses/job-category/details?mode=add',
  [DashboardPageType.JOB_CLASSIFICATION_TYPE]: '/apps/ses/job-classification-type/details?mode=add',
  [DashboardPageType.JOB_LEVEL]: '/apps/ses/job-level/details?mode=add',
  [DashboardPageType.SEASONAL_JOB_APP_SETTING]: '/apps/ses/seasonal-job-app-setting/details?mode=add',
  [DashboardPageType.TIME_PERIOD]: '/apps/ses/time-period/details?mode=add',
  // DEF (Common)
  [DashboardPageType.COUNTRY]: '/apps/def/country/details?mode=add',
  [DashboardPageType.CITY]: '/apps/def/city/details?mode=add',
  [DashboardPageType.NATIONALITY]: '/apps/def/nationality/details?mode=add',
  [DashboardPageType.BANK]: '/apps/def/bank/details?mode=add',
  [DashboardPageType.JOB]: '/apps/def/job/details?mode=add',
  [DashboardPageType.LANGUAGE]: '/apps/def/language/details?mode=add',
  [DashboardPageType.PORT]: '/apps/def/port/details?mode=add',
  [DashboardPageType.SEASON]: '/apps/def/season/details?mode=add',
  [DashboardPageType.TERMINAL]: '/apps/def/terminal/details?mode=add',
  [DashboardPageType.BUS_TYPE]: '/apps/def/bus-type/details?mode=add',
  [DashboardPageType.CAR_TYPE]: '/apps/def/car-type/details?mode=add',
  [DashboardPageType.LOCATION]: '/apps/def/location/details?mode=add',
  [DashboardPageType.DEPARTMENT]: '/apps/def/department/details?mode=add',
  [DashboardPageType.ATTACHMENT_CATEGORY]: '/apps/def/attachment-category/details?mode=add',
  [DashboardPageType.REPRESENTATIVE]: '/apps/def/representative/details?mode=add',
  [DashboardPageType.ROUTE]: '/apps/def/route/details?mode=add',
  [DashboardPageType.SERVER]: '/apps/def/server/details?mode=add',
  [DashboardPageType.DEF_PATH]: '/apps/def/path/details?mode=add',
  [DashboardPageType.PAYMENT_METHOD]: '/apps/def/payment-method/details?mode=add',
  [DashboardPageType.EMPLOYMENT_STATUS]: '/apps/def/employment-status/details?mode=add',
  [DashboardPageType.AGE_STAGE]: '/apps/def/age-stage/details?mode=add',
  [DashboardPageType.DEPARTMENT_TYPE]: '/apps/def/department-type/details?mode=add',
  [DashboardPageType.HAJ_COMPANY_TYPE]: '/apps/def/haj-company-type/details?mode=add',
  [DashboardPageType.HAJ_TYPE]: '/apps/def/haj-type/details?mode=add',
  [DashboardPageType.HOUSE_AGENT_TYPE]: '/apps/def/house-agent-type/details?mode=add',
  [DashboardPageType.HOUSE_BENEFIT_TYPE]: '/apps/def/house-benefit-type/details?mode=add',
  [DashboardPageType.HOUSE_INVESTOR_TYPE]: '/apps/def/house-investor-type/details?mode=add',
  [DashboardPageType.HOUSE_OWNER_TYPE]: '/apps/def/house-owner-type/details?mode=add',
  [DashboardPageType.HOUSE_TYPE]: '/apps/def/house-type/details?mode=add',
  [DashboardPageType.LAND_TRAN_COMPANY]: '/apps/def/land-tran-company/details?mode=add'
}
